name: yajbe
description: YAJBE is a compact binary data format built to be a drop-in replacement for JSON (JavaScript Object Notation).
version: 0.9.3
homepage: https://github.com/matteobertozzi/yajbe-data-format
repository: https://github.com/matteobertozzi/yajbe-data-format
issue_tracker: https://github.com/matteobertozzi/yajbe-data-format/issues

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
